#include "agrisphere/services/RegistrationService.h"

#include "agrisphere/core/Strings.h"
#include "agrisphere/db/DatabaseManager.h"

#include <cctype>
#include <exception>

namespace agri {
namespace service {
namespace {

// Approximates PHP's FILTER_VALIDATE_EMAIL for the shapes this form accepts.
bool isValidEmail(const std::string& email) {
    const std::size_t at = email.find('@');
    if (at == std::string::npos || at == 0 || at + 1 >= email.size()) {
        return false;
    }
    if (email.find('@', at + 1) != std::string::npos) {
        return false;
    }
    const std::string domain = email.substr(at + 1);
    const std::size_t dot = domain.find('.');
    if (dot == std::string::npos || dot == 0 || dot + 1 >= domain.size()) {
        return false;
    }
    for (const char c : email) {
        if (std::isspace(static_cast<unsigned char>(c))) {
            return false;
        }
    }
    return true;
}

bool isSixDigits(const std::string& value) {
    if (value.size() != 6) {
        return false;
    }
    for (const char c : value) {
        if (!std::isdigit(static_cast<unsigned char>(c))) {
            return false;
        }
    }
    return true;
}

json::Value failure(const std::string& message, const std::string& kind = std::string()) {
    json::Value out = json::Value::object();
    out.set("success", json::Value(false));
    out.set("error", json::Value(message));
    if (!kind.empty()) {
        out.set("error_kind", json::Value(kind));
    }
    return out;
}

} // namespace

json::Value RegistrationService::start(const RegistrationRequest& request) {
   
    json::Value errors = json::Value::array();
    auto add = [&errors](const char* message) { errors.push(json::Value(message)); };

    if (request.firstName.empty()) add("First name is required");
    if (request.lastName.empty()) add("Last name is required");
    if (request.username.empty()) add("Username is required");
    if (request.email.empty()) add("Email is required");
    if (!isValidEmail(request.email)) add("Invalid email format");
    if (request.phone.empty()) add("Phone number is required");
    if (request.address.empty()) add("Address is required");
    if (request.password.empty()) add("Password is required");
    if (request.password.size() < 6) add("Password must be at least 6 characters");
    if (request.password != request.confirmPassword) add("Passwords do not match");
    if (request.role != "Farmer" && request.role != "Customer") add("Invalid role selected");

    if (users_.usernameExists(request.username)) {
        add("Username already taken. Please choose another.");
    }
    if (users_.emailExists(request.email)) {
        add("Email already registered. Please use another email or login.");
    }

    if (errors.size() > 0) {
        json::Value out = json::Value::object();
        out.set("success", json::Value(false));
        out.set("errors", errors);
        return out;
    }

    repo::PendingRegistration record;
    record.firstName = request.firstName;
    record.lastName = request.lastName;
    record.username = request.username;
    record.password = request.password;
    record.userType = request.role;
    record.phone = request.phone;
    record.email = request.email;
    record.address = request.address;
    // Demo NID, as generated by the previous handler.
    record.nid = std::to_string(1 + (strings::randomDigits(1)[0] - '0') % 9) +
                 strings::randomDigits(9);
    record.otpCode = strings::randomDigits(6);
    record.expiresAt = strings::nowDateTime(config_.otpLifetimeMinutes * 60);

    pending_.deleteByEmail(request.email);
    pending_.insertPending(record);

    json::Value out = json::Value::object();
    out.set("success", json::Value(true));
    out.set("email", json::Value(record.email));
    out.set("role", json::Value(record.userType));
    out.set("otp", json::Value(record.otpCode));
    out.set("expires_at", json::Value(record.expiresAt));
    return out;
}

json::Value RegistrationService::verify(const std::string& email, const std::string& otp) {
    if (!isSixDigits(otp)) {
        return failure("Please enter a valid 6-digit OTP", "otp_format");
    }

    const auto valid = pending_.findValid(email, otp);
    if (!valid) {
        const auto any = pending_.findByEmail(email);
        if (!any) {
            return failure("Registration session expired. Please register again.",
                           "session_expired");
        }
        if (any->expiresAt < strings::nowDateTime()) {
            return failure("OTP has expired. Please request a new one.", "otp_expired");
        }
        return failure("Invalid OTP. Please try again.", "otp_invalid");
    }

    
    if (users_.usernameExists(valid->username)) {
        pending_.deleteByEmail(email);
        return failure("Username already taken. Please register again with a different username.",
                       "username_taken");
    }
    if (users_.emailExists(valid->email)) {
        pending_.deleteByEmail(email);
        return failure("Email already registered. Please login instead.", "email_taken");
    }

    long long userId = 0;
    try {
        db::PooledConnection connection = db::DatabaseManager::getInstance().acquire();
        db::Transaction transaction(connection);

        userId = users_.createVerifiedUser(connection, valid->firstName, valid->lastName,
                                           valid->username, valid->password, valid->userType,
                                           valid->phone, valid->email, valid->nid);
        if (userId <= 0) {
            // The guard rolls back when it leaves this scope.
            return failure("Registration failed. Please try again.", "insert_failed");
        }

       
        if (valid->userType == "Farmer") {
            users_.upsertFarmerProfile(connection, userId, valid->address);
        } else {
            users_.upsertCustomerProfile(connection, userId, valid->address, valid->phone);
        }

        transaction.commit();
    } catch (const std::exception&) {
        
        return failure("Registration failed. Please try again.", "insert_failed");
    }

    pending_.deleteByEmail(email);
    users_.recordLogin(userId);

    json::Value session = json::Value::object();
    session.set("user_id", json::Value(userId));
    session.set("user_name", json::Value(valid->firstName + " " + valid->lastName));
    session.set("user_type", json::Value(valid->userType));
    session.set("username", json::Value(valid->username));
    session.set("first_name", json::Value(valid->firstName));

    json::Value out = json::Value::object();
    out.set("success", json::Value(true));
    out.set("session", session);
    out.set("redirect", json::Value(valid->userType == "Farmer" ? "farmer/dashboard.php"
                                                                : "customer/dashboard.php"));
    return out;
}

json::Value RegistrationService::resend(const std::string& email) {
    const auto any = pending_.findByEmail(email);
    if (!any) {
        return failure("Registration session expired. Please register again.", "session_expired");
    }

    const std::string otp = strings::randomDigits(6);
    const std::string expiresAt = strings::nowDateTime(config_.otpLifetimeMinutes * 60);
    pending_.updateOtp(email, otp, expiresAt);

    json::Value out = json::Value::object();
    out.set("success", json::Value(true));
    out.set("otp", json::Value(otp));
    out.set("expires_at", json::Value(expiresAt));
    return out;
}

} // namespace service
} // namespace agri
